name: raywenderlich_offline_downloader
description: Download videos from Raywenderlich for offline use.
# version: 1.0.0

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  args: ^1.6.0
  http: ^0.12.2
  puppeteer: ^1.18.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
