name: raywenderlich_offline_downloader
description: Download videos from Raywenderlich for offline use.
# version: 1.0.0

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  json_serializable: ^3.4.1
  freezed_annotation: ^0.11.0
  args: ^1.6.0
  http: ^0.12.2
  puppeteer: ^1.18.0

dev_dependencies:
  build_runner: ^1.10.0
  freezed: ^0.11.0
  pedantic: ^1.8.0
  test: ^1.6.0

dependency_overrides:
  analyzer: '0.39.14'